# Generated by Django 4.0.4 on 2022-05-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='distance',
        ),
    ]
